# Generated by Django 4.2.2 on 2023-10-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_user_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='members',
        ),
    ]
